# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  image: testing

# Build documentation in the myfossdocs/ directory with Sphinx
sphinx:
   configuration: myfossdocs/source/conf.py

# Optionally build your docs in additional formats such as PDF
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  version: "3.9"
  install:
    - extra_requirements:
        - myfossdocs
  
 
